chore: replace from with_capacity with try_reserve
y-crdt/y-crdt pull request #369
Opened 2023-12-18 17:05 UTC by appflowy

Replace the use of `with_capacity` with `try_reserve` in collections specifically when decoding the `Update` to better handle potential memory allocation errors. For now, this change should be applied only in the context of `Update` decoding, without altering other instances of `with_capacity` usage.

2023-12-19 08:52 UTC, Horusiath commented
This is a little bit tricky. A fact that you've allocated enough space for blocks alone doesn't mitigate all the issues. You can have enough memory to allocate blocks, but still not enough to allocate block-related data.

2023-12-19 16:48 UTC, appflowy commented
Yes, refactoring is necessary for managing block-related data more effectively. In the current setup, decoding invalid data leads to a memory allocation error, which results in the immediate termination of the program. One approach I'm considering to prevent this issue is implementing 'Input Validation.' This would involve checking the data before decoding to ensure it adheres to the expected format and constraints, thereby avoiding the decoding of manifestly invalid data. Do you think this would be an effective solution, or do you have any other recommendations?

2023-12-21 20:58 UTC, Horusiath requested changes
If this is an approach to fight with malicious or corrupted updates, then we'd need to specify what is a max allowed update size and verify it after decoding the clients/block length.

But since it's hard to determine these limits before reading the entire update, the proactive approach with `try_reserve` seems to be plausible. My only note is an error name - please change it to better indicate that it's a memory allocation problem.

2023-12-21 20:58 UTC, Horusiath commented on yffi/src/lib.rs
> +pub const ERR_NOT_ENOUGH_BYTES: u8 = 7;
Maybe `ERR_NOT_ENOUGH_MEMORY`?

2023-12-21 20:58 UTC, Horusiath commented on yrs/src/encoding/read.rs
> +    NotEnoughBytes(#[from] TryReserveError),
Same here, `NotEnoughMemory` seems to be better description of the problem.

2023-12-21 21:03 UTC, appflowy commented
> If this is an approach to fight with malicious or corrupted updates, then we'd need to specify what is a max allowed update size and verify it after decoding the clients/block length.
> 
> But since it's hard to determine these limits before reading the entire update, the proactive approach with `try_reserve` seems to be plausible. My only note is an error name - please change it to better indicate that it's a memory allocation problem.

Got it. Will do later

2024-01-17 05:29 UTC, appflowy commented
@Horusiath Is there anything else I need to do for this pull request before it can be merged?

2024-01-17 10:56 UTC, Horusiath commented
@appflowy I see there are merge conflicts. I can take it over from here and merge it this week.

2024-01-19 05:26 UTC, appflowy commented
> @appflowy I see there are merge conflicts. I can take it over from here and merge it this week.

Done

2024-01-19 08:00 UTC, Horusiath approved these changes

2024-01-19 08:00 UTC, merged