[WIP] Moving Block::Skip outside of default Block impl
y-crdt/y-crdt pull request #87
Opened 2022-02-14 08:52 UTC by Horusiath

2022-02-14 08:54 UTC, Horusiath commented on yrs/benches/benches.rs
> +fn b4_2(c: &mut Criterion, name: &str) {
I've added a benchmark that's used solely for checking out how long will it take to apply update generated from B4.1 (real live edit trace). Apparently applying update that's almost 400kB takes ~2-3ms.

2022-02-14 08:55 UTC, Horusiath commented on yrs/src/block.rs
> -            Block::Skip(skip) => ID::new(skip.id.client, skip.id.clock + skip.len),
Since `Block::Skip` doesn't exists in block store (only used in context of update), I removed this case from default `Block` definition.

2022-02-14 08:55 UTC, Horusiath commented on yrs/src/block.rs
> +pub struct BlockRange {
`BlockRange` covers similarities between `Skip` and `GC` blocks.

2022-02-14 08:57 UTC, Horusiath commented on yrs/src/block.rs
> +    pub fn try_eq(&self, other: &Item) -> Option<bool> {
I changed `Item::eq` in a way that assumes, that two items may have different neighbor `BlockPtr`'s, which are not structurally equatable, but still may point to the same blocks. Problem is that establishing equality in such way requires access to block store (in order to navigate to left/right neighbor), therefore without having it it's not always possible to do so.

2022-02-14 09:00 UTC, Horusiath commented on yrs/src/block.rs
> +            len // quite often strings are single-letter, so we don't care about OffsetKind
Micro optimization to make computing lengths for single-char strings faster (which is quite common in transaction-per-keystroke case). Problem is that it still doesn't bring enough of speedup in terms of cached `Item::len` field. We might possibly make this field to be calculated lazily.

2022-02-14 09:00 UTC, Horusiath commented on yrs/src/block.rs
> -    utf16_len: usize,
Since `Item::len` now contains precomputed field length, it doesn't have to reside here anymore.

2022-02-14 09:02 UTC, Horusiath commented on yrs/src/update.rs
> +    Skip(BlockRange),
`BlockCarrier` is essentially a wrapper around `Block` which extends it to cover `Skip` semantics for update structure purposes.

2022-02-15 10:09 UTC, dmonad requested changes

2022-02-15 10:09 UTC, dmonad commented on yrs/src/update.rs
> +    fn eq(&self, other: &Self) -> bool {
We can simplify this as left/right should always be none.

2022-02-22 11:10 UTC, merged